Being able to add buttons to the right of the subject line in thread view
InboxSDK/InboxSDK pull request #1121
Opened 2024-02-07 20:56 UTC by ruthhalteman

Streak example is our streak share button. Next to gmail's print and open in new buttons.

Currently draft because I don't know how correct or robust this is. So far the main issue I see is that it's not finding the container in the reading pane views. Not sure why, the subject line label (existing functionality) is fine and works in a very similar way.

2024-02-07 20:57 UTC, ruthhalteman commented on src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts
> +    el.setAttribute('data-unique-tt-id', 'ucc-2');
oh yeah and it shouldn't be hardcoded to 2 if this is actually kept in here. should be consecutive like the gmail ones are

2024-02-07 21:18 UTC, wegry reviewed
Looks pretty good so far.

I did notice the subject button disappearing after 5s or so with the reading pane enabled...

See https://www.loom.com/share/0dc58ca527294d7598dffb813600ae6d

2024-02-07 21:18 UTC, wegry commented on src/platform-implementation-js/views/conversations/thread-view.ts
> +  addSubjectButton(buttonDescriptor: Record<string, any>) {
Could we use https://github.com/InboxSDK/InboxSDK/blob/4edf7ccd5e69417933291d69006d111f7bfc4bf7/src/inboxsdk.d.ts#L446 here?

```suggestion
  addSubjectButton(buttonDescriptor: Descriptor<ButtonDescriptor>) {
```

2024-02-07 21:18 UTC, wegry commented on src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts
> +  _findSubjectToolbarElement(): HTMLElement | null | undefined {
Unless we want this method visible outside the class...

```suggestion
  #findSubjectToolbarElement(): HTMLElement | null {
```

2024-02-07 21:18 UTC, wegry commented on src/platform-implementation-js/views/conversations/thread-view.ts
> +  addSubjectButton(buttonDescriptor: Record<string, any>) {
If we don't necessarily want an `Observable` as part of the API, an alternative would be 

```suggestion
  addSubjectButton(buttonDescriptor: ButtonDescriptor) {
```

2024-02-07 21:18 UTC, wegry commented on src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts
> +  addSubjectButton(button: any) {
We might use either `ButtonDescriptor` or `Descriptor<ButtonDescriptor>` as the type here.

2024-02-14 16:59 UTC, wegry commented on src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts
> +    return toolbarContainerElements[0];
What's the rationale for querySelectorAll here?

Maybe we just want:

```suggestion
    const toolbarContainerElement =
       this._element.querySelector<HTMLElement>('.bHJ');
     return toolbarContainerElement;
```

2024-02-14 17:03 UTC, wegry requested changes
Alright, so running through this example extension with the reading pane enabled and not looks good.

Few things I'd like to see changed prior to pulling it in are (in order):

1. Use `SelectorError` for reporting's sake when an element isn't present and we expect it to be so.
1. Plumb the ButtonDescriptor all the way through from the public interface (removing some remaining `any`s).
2. Not adding new non public methods to gmail-thread-view).

2024-04-15 18:38 UTC, wegry approved these changes

2024-04-15 18:45 UTC, wegry commented on src/platform-implementation-js/views/conversations/thread-view.ts
> +
```suggestion
  /**
   * @internal
   */
```

2024-04-15 19:33 UTC, merged